version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    groups:
      lint-and-types:
        patterns:
          - "eslint*"
          - "@eslint/*"
          - "@types/*"
          - "typescript-eslint"
    ignore:
      - dependency-name: vinext
      - dependency-name: "@vitejs/plugin-rsc"
